/**
 * Skill Demos — showcase a variety of A2UI v0.9 component trees
 * generated by the a2ui-generation skill.
 *
 * Each story uses a left-right layout:
 * - Left:  JSON source (components / data model tabs)
 * - Right: live A2UI rendering
 */
import type { Meta, StoryObj } from '@storybook/react';
import React from 'react';

import { SkillDemoLayout } from './SkillDemoLayout';
import type { SkillDemoData } from './SkillDemoLayout';

// Demo data imports
import productComponents from './skill-demos/product-card.json';
import productData from './skill-demos/product-card-data.json';
import taskComponents from './skill-demos/task-dashboard.json';
import taskData from './skill-demos/task-dashboard-data.json';
import pricingComponents from './skill-demos/pricing-card.json';
import pricingData from './skill-demos/pricing-card-data.json';
import notifComponents from './skill-demos/notification-center.json';
import notifData from './skill-demos/notification-center-data.json';
import orderComponents from './skill-demos/order-summary.json';
import orderData from './skill-demos/order-summary-data.json';
import teamComponents from './skill-demos/team-card.json';
import teamData from './skill-demos/team-card-data.json';
import profileComponents from './skill-demos/user-profile-components.json';
import profileData from './skill-demos/user-profile-datamodel.json';

const meta: Meta<typeof SkillDemoLayout> = {
  title: 'Skill Demos',
  component: SkillDemoLayout,
};
export default meta;
type Story = StoryObj<typeof SkillDemoLayout>;

// ---- Helpers ----

function demo(
  components: unknown,
  dataModel: unknown,
  description: string,
  surfaceWidth?: number,
): Story {
  return {
    render: () => (
      <SkillDemoLayout
        demo={components as SkillDemoData['components'] & SkillDemoData['dataModel'] & { components: SkillDemoData['components']; dataModel: SkillDemoData['dataModel'] } as unknown as SkillDemoData}
        description={description}
        surfaceWidth={surfaceWidth ?? 420}
      />
    ),
  };
}

// Actually, let's just use a simpler typed wrapper
function makeDemo(
  compJson: unknown,
  dataJson: unknown,
  description: string,
  surfaceWidth?: number,
): Story {
  return {
    render: () => {
      const demoData: SkillDemoData = {
        components: compJson as SkillDemoData['components'],
        dataModel: dataJson as SkillDemoData['dataModel'],
      };
      return (
        <SkillDemoLayout
          demo={demoData}
          description={description}
          surfaceWidth={surfaceWidth ?? 420}
        />
      );
    },
  };
}

// ---- Stories ----

export const UserProfileCard = makeDemo(
  profileComponents,
  profileData,
  'A user profile card with avatar, statistics, skill tags, and action button. Demonstrates data binding with { "path": "..." } syntax for avatar URL, name, role, stats, and tags.',
  440,
);

export const ProductCard = makeDemo(
  productComponents,
  productData,
  'An e-commerce product card featuring image display, price, rating stars, category tags, and an "Add to Cart" action button.',
  360,
);

export const TaskDashboard = makeDemo(
  taskComponents,
  taskData,
  'A sprint task dashboard with colored statistic cards, a progress bar, and a task list with status tags.',
  480,
);

export const PricingCard = makeDemo(
  pricingComponents,
  pricingData,
  'A SaaS pricing plan card with plan name, price, feature list, and a full-width CTA button.',
  320,
);

export const NotificationCenter = makeDemo(
  notifComponents,
  notifData,
  'A notification panel with alert banners (success, warning), a timeline of recent activity, and an "unread" badge.',
  440,
);

export const OrderSummary = makeDemo(
  orderComponents,
  orderData,
  'An order summary card with item rows, total price, shipping details via Descriptions component, and action buttons.',
  440,
);

export const TeamCard = makeDemo(
  teamComponents,
  teamData,
  'A team roster card with team-level statistics and a member list showing avatars, names, roles, and role tags.',
  440,
);
