/**
 * Skill demo: render the user profile card generated by the a2ui-generation skill.
 */
import type { Meta, StoryObj } from '@storybook/react';
import React, { useEffect, useRef } from 'react';

import { GenUISurface } from '../src/components/Surface';
import { SurfaceManager } from '../src/SurfaceManager';

import '../src/components/index';

import componentsJson from '../.vibe/user_profile_components.json';
import dataModelJson from '../.vibe/user_profile_datamodel.json';

const meta: Meta<typeof GenUISurface> = {
  title: 'Skill Demo/User Profile Card',
  component: GenUISurface,
};
export default meta;

type Story = StoryObj<typeof GenUISurface>;

const UserProfileDemo: React.FC = () => {
  const managerRef = useRef<SurfaceManager>(new SurfaceManager());

  useEffect(() => {
    const m = managerRef.current;
    const comp = componentsJson as Record<string, unknown>;
    const data = dataModelJson as Record<string, unknown>;

    const surfaceId = (comp.updateComponents as Record<string, unknown>)?.surfaceId as string;
    const theme = (comp.updateComponents as Record<string, unknown>)?.theme as Record<string, string> ?? {};

    m.getEngine().createSurface(surfaceId, 'genui-antd', theme);

    const components = ((comp.updateComponents as Record<string, unknown>)?.components as unknown[]) ?? [];
    m.getEngine().updateComponents(surfaceId, components.map((c: unknown) => JSON.stringify(c)));

    const dm = data.updateDataModel as Record<string, unknown>;
    if (dm) {
      m.getEngine().updateDataModel(
        surfaceId,
        (dm.path as string) || '/',
        dm.value,
      );
    }
  }, []);

  return (
    <div style={{ display: 'flex', justifyContent: 'center', padding: 48, background: '#f5f5f5' }}>
      <GenUISurface
        surfaceManager={managerRef.current}
        width={520}
        height={400}
        style={{ background: '#fff', borderRadius: 12 }}
      />
    </div>
  );
};

export const UserProfileCard: Story = {
  name: 'User Profile Card (Skill Output)',
  render: () => <UserProfileDemo />,
};
